<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MISA.Salary.BL\MISA.Salary.BL.csproj" />
    <ProjectReference Include="..\MISA.Salary.Common\MISA.Salary.Common.csproj" />
    <ProjectReference Include="..\MISA.Salary.DL\MISA.Salary.DL.csproj" />
  </ItemGroup>

</Project>
